spring.application.name=smartpark
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
server.port=${PORT:8080}

app.bank.account=0707561652
app.bank.owner=NGUYEN THANH HUY
app.bank.name=MB

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

resend.api.key=${RESEND_API_KEY}
app.email.from=${RESEND_FROM_EMAIL:onboarding@resend.dev}

spring.security.user.name=disable
spring.security.user.password=disable

logging.level.org.thymeleaf=WARN
spring.thymeleaf.cache=true