spring.application.name=smartpark
server.port=${PORT:8080}

app.bank.account=0707561652
app.bank.owner=NGUYEN THANH HUY
app.bank.name=MB

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

resend.api.key=${RESEND_API_KEY}


spring.security.user.name=disable
spring.security.user.password=disable

logging.level.org.thymeleaf=WARN
spring.thymeleaf.cache=true